version: '2'
services:
  jhipster2020-app:
    image: jhipster2020
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://jhipster2020-postgresql:5432/JHipster2020
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  jhipster2020-postgresql:
    extends:
      file: postgresql.yml
      service: jhipster2020-postgresql
